[workspace]

members = [
    "defable",
    "fable",
    "fable_binding",
    "fable_bot",
    "fable_hack",
    "fable_randize",
    "fable2",
    "refable",
]

exclude = [
    "defable.netlify.com",
    "fable_blender",
]