[package]
name = "open_albion"
version = "0.1.0"
authors = ["Jamen Marz <me@jamen.dev>"]
edition = "2018"
license = "Zlib"
homepage = "https://github.com/jamen/open_albion"
repository = "https://github.com/jamen/open_albion"
# documentation = "https://docs.rs/fable_data"

[dependencies]
bytemuck = "1.2.0"
clap = "2.33.3"
cpal = "0.11.0"
env_logger = "0.8.2"
fontdue = "0.4.0"
futures = "0.3.5"
glam = "0.11.2"
hecs = "0.2.12"
log = "0.4.8"
nfd = "0.0.4"
nom = "5.1.2"
num_cpus = "1.13.0"
rodio = "0.13.0"
smol = "0.1.18"
spin_sleep = "1.0.0"
vk-shader-macros = "0.2.6"
wgpu = "0.6.0"
winit = "0.22.1"

[dev-dependencies]
hex_table = "0.1.4"
rand = "0.7.3"
