[workspace]

members = [
    "crates/defable",
    "crates/fable_anim",
    "crates/fable_archive",
    "crates/fable_audio",
    "crates/fable_base",
    "crates/fable_cheat",
    "crates/fable_defs",
    "crates/fable_level",
    "crates/fable_mesh",
    "crates/fable_mod_pack",
    "crates/fable_save",
    "crates/fable_script",
]

[patch.crates-io]
fable_anim = { version = "0.1.0", path = "crates/fable_anim" }
fable_archive = { version = "0.1.0", path = "crates/fable_archive" }
fable_audio = { version = "0.1.0", path = "crates/fable_audio" }
fable_base = { version = "0.1.0", path = "crates/fable_base" }
fable_cheat = { version = "0.1.0", path = "crates/fable_cheat" }
fable_defs = { version = "0.1.0", path = "crates/fable_defs" }
fable_level = { version = "0.1.0", path = "crates/fable_level" }
fable_mesh = { version = "0.1.0", path = "crates/fable_mesh" }
fable_mod_pack = { version = "0.1.0", path = "crates/fable_mod_pack" }
fable_save = { version = "0.1.0", path = "crates/fable_save" }
fable_script = { version = "0.1.0", path = "crates/fable_script" }