[package]
name = "unfable"
version = "0.1.0"
authors = ["Jamen Marz <me@jamen.dev>"]
edition = "2018"

[lib]
name = "unfable"
path = "src/lib.rs"

[[bin]]
name = "unfable"
path = "src/main.rs"

[dependencies]
nom = "5.0.1"
chrono = "0.4.9"
winapi = "0.3.8"