[workspace]

members = [
    "crates/defable",
    "crates/defable_editor/native",
    "crates/defable_cheat",
    "crates/fable",
    "crates/refable",
]

[patch.crates-io]
fable = { version = "0.1.0", path = "crates/fable" }