[workspace]
members = [
    "defable",
    "fable",
    "fable_binding",
    "fable_hack",
    "fable_hack_randize",
    "fable_hack_tas",
    "fable2",
]
exclude = [
    "defable.netlify.com",
    "fable_edit",
    "fable_js/native",
]