[workspace]

members = [
    "crates/defable",
    "crates/defable_launcher/native",
    "crates/fable_cheat",
    "crates/fable_format",
    "crates/fable_gltf",
]

[patch.crates-io]
fable_cheat = { path = "crates/fable_cheat" }
fable_format = { path = "crates/fable_format" }
fable_gltf = { path = "crates/fable_gltf" }