[package]
name = "fable_transfer"
version = "0.1.0"
authors = ["Jamen Marz <me@jamen.dev>"]
edition = "2018"

[[bin]]
name = "fable_transfer"
path = "src/bin/fable_transfer.rs"

[dependencies]
clap = "2.33.0"
fable = { path = "../fable" }
gltf-json = "0.14.0"