[package]
name = "fable_randize"
version = "0.1.0"
authors = ["Jamen Marz <me@jamen.dev>"]
edition = "2018"

[[bin]]
name = "fable_randize"
path = "src/bin/fable_randize.rs"

[dependencies]
clap = "2.33.0"