[package]
name = "unfable_parser"
version = "0.1.0"
authors = ["Jamen Marz <me@jamen.dev>"]
edition = "2018"

[lib]
name = "unfable_parser"
path = "src/lib.rs"

[dependencies]
nom = "5.0.1"
chrono = "0.4.9"