[package]
name = "defable"
version = "0.1.0"
authors = ["Jamen Marz <me@jamen.dev>"]
edition = "2018"

[dependencies]
fable_format = "0.1.0"
fable_gltf = "0.1.0"
fable_cheat = "0.1.0"
fable_launch = "0.1.0"
gltf-json = "0.14.0"
clap = "2.33.0"
gfx = "0.18.2"