[package]
name = "fable_blender"
version = "0.1.0"
authors = ["Jamen Marz <me@jamen.dev>"]
edition = "2018"

[lib]
name = "fable_blender"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
fable = { path = "../fable" }