<<<<<<< HEAD
[workspace]
members = [
    "open_albion"
]
=======
[package]
name = "fable_data"
version = "0.1.1"
authors = ["Jamen Marz <me@jamen.dev>"]
edition = "2018"
description = "A Rust library for using the assets of Fable, Fable: The Lost Chapters, Fable Anniversary, and mods."
readme = "readme.md"
license = "Zlib"
homepage = "https://github.com/jamen/open_albion/tree/master/fable_data"
repository = "https://github.com/jamen/open_albion"
documentation = "https://docs.rs/fable_data"

[dependencies]
nom = "5.0.1"
chrono = "0.4.9"
>>>>>>> fable_data/master
