[package]
name = "fable_data"
version = "0.1.1"
authors = ["Jamen Marz <me@jamen.dev>"]
edition = "2018"
description = "A Rust library for using Fable's data."
readme = "readme.md"
license = "Zlib"
homepage = "https://github.com/jamen/fable_data"
repository = "https://github.com/jamen/fable_data"
documentation = "https://docs.rs/fable_data"

[dependencies]
nom = "5.1.2"
hex_table = "0.1.4"

[dev-dependencies]
rand = "0.7.3"
hex_table = "0.1.4"
# coder = { git = "https://github.com/jamen/io-utils", branch = "master" }
# nib = { git = "https://github.com/jamen/io-utils", branch = "master" }
# subsource = { git = "https://github.com/jamen/io-utils", branch = "master" }

# [patch."https://github.com/jamen/io-utils"]
# coder = { path = "../io-utils/coder" }
# nib = { path = "../io-utils/nib" }
# subsource = { path = "../io-utils/subsource" }